version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    
    working-directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
        keys:
        - v1-dependencies-
        # fallback using latest cache if no exact match found
        - v1-dependencies-

      - run:
        name: Install serverless CLI & dependencies
        command: |
          sudo npm i -g serverless
          npm install
 
      - save_cache:
        paths:
          - node_modules
        keys: v1-dependencies-

      # run-tests
      - run:
          name: Run tests with coverage
          command: npm test --coverage
 
      - run: 
          name: Deploy application
          command: sls deploy --stage pre
